include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true
  plugins:
    - custom_lint
linter:
  rules:
    - avoid_dynamic_calls
    - avoid_void_async
    - comment_references
    - directives_ordering
    - prefer_relative_imports
    - sort_pub_dependencies
